import type { BotConfig } from "../src/config.js";
import type { TokenBook, UpDownEvent } from "../src/types.js";

export function testConfig(overrides: Partial<BotConfig> = {}): BotConfig {
  return {
    exchange: "polymarket",
    strategyMode: "odahoa_ladder",
    executionMode: "paper",
    pollIntervalMs: 5_000,
    marketSlugPrefixes: ["btc-updown-15m"],
    cheapBuyMin: 0.07,
    cheapBuyMax: 0.1,
    expensiveBuyMin: 0.9,
    expensiveBuyMax: 0.95,
    enableExpensiveHedge: true,
    cheapOrderUsdc: 10,
    expensiveOrderUsdc: 50,
    maxSharesPerOrder: 90,
    minutesBeforeCloseMin: 0,
    minutesBeforeCloseMax: 15,
    dryRun: true,
    signatureType: 3,
    clobHost: "https://clob.polymarket.com",
    chainId: 137,
    gammaApiHost: "https://gamma-api.polymarket.com",
    kalshiApiHost: "https://external-api.kalshi.com/trade-api/v2",
    kalshiWsHost: "wss://external-api-ws.kalshi.com/trade-api/ws/v2",
    kalshiSeriesTickers: ["KXBTC15M"],
    kalshiSubaccount: 0,
    kalshiTakerFeeRate: 0.07,
    kalshiMakerFeeRate: 0,
    kalshiFeeOverrides: {},
    ladderPreset: "odahoa_v1",
    ladderSizeScale: 1,
    ladderMaxUsdcPerMarket: 65,
    staticMakerMaxShares: 90,
    staticMakerMaxUsdcPerMarket: 500,
    pairLockMaxCost: 0.985,
    pairLockResidualFraction: 0.1,
    pairLockResidualMaxPrice: 0.2,
    ladderV5MaxImbalance: 70,
    ladderV5MaxPairCost: 0.98,
    ladderV6MaxUnmatchedShares: 40,
    ladderV6MinNetEdge: 0.01,
    ladderV6SafetyBuffer: 0.01,
    ladderV6MaxRescueLoss: 0.02,
    ladderV7CheapPrice: 0.1,
    ladderV7FavoritePrice: 0.8,
    ladderV7MaxShares: 40,
    ladderV8SizeScale: 1,
    ladderV8MaxSharesPerOrder: 120,
    ladderV8MaxUnmatchedShares: 240,
    ladderV9CheapPrice: 0.1,
    ladderV9InitialFavoritePrice: 0.8,
    ladderV9InitialFavoriteShares: 20,
    ladderV9TargetShares: 40,
    ladderV9MinLockedEdge: 0.03,
    ladderV9CompletionRetryLimit: 4,
    ladderV9CompletionCooldownMs: 350,
    ladderV9RescueMaxPairCost: 1,
    ladderV9EmergencyMaxPairCost: 1.02,
    ladderV9ManagementCutoffSeconds: 15,
    ladderV10CheapPrice: 0.1,
    ladderV10FavoritePrice: 0.8,
    ladderV10MidShares: 20,
    ladderV10TargetShares: 40,
    ladderV10MaxPairCost: 0.97,
    ladderV10ScoreLow: 40,
    ladderV10ScoreHigh: 70,
    ladderV10BurnInMarkets: 32,
    ladderV10SnapshotIntervalMs: 1_000,
    ladderV10SourceStaleMs: 2_000,
    ladderV10CoinbaseWsHost: "wss://advanced-trade-ws.coinbase.com",
    ladderV10CoinbaseProduct: "BTC-USD",
    ladderV14PriorStrength: 5,
    ladderV14FlowWindowSeconds: 60,
    ladderV14VolatilityWindowSeconds: 60,
    ladderV14FinalCleanupSeconds: 30,
    ladderV14QuoteLifetimeSeconds: 5,
    ladderV14PseudoFlowDepthFraction: 1,
    ladderV14QuantityQueueWeight: 1,
    ladderV14ReachabilityMultiplier: 1.5,
    ladderV14VolumeFirstMode: false,
    ladderV14CycleShares: 10,
    ladderV14VolumeFirstPairCost: 0.99,
    paperStartingUsdc: 100,
    paperStatePath: "./data/test-paper",
    ...overrides,
  };
}

export function testEvent(): UpDownEvent {
  return {
    title: "Bitcoin Up or Down - Test",
    slug: "btc-updown-15m-1000000000",
    windowStart: 1_000_000_000,
    windowEnd: 1_000_000_900,
    market: {
      id: "123",
      question: "Bitcoin Up or Down?",
      conditionId: "condition",
      slug: "btc-updown-15m-1000000000",
      clobTokenIds: JSON.stringify(["up-token", "down-token"]),
      outcomes: JSON.stringify(["Up", "Down"]),
      negRisk: false,
      orderPriceMinTickSize: 0.01,
      active: true,
      closed: false,
    },
  };
}

export function testBooks(
  upAsk = 0.4,
  downAsk = 0.6,
  minimumSize = 0,
): TokenBook[] {
  return [
    {
      tokenId: "up-token",
      outcome: "Up",
      outcomeIndex: 0,
      bestBid: 0.39,
      bestAsk: upAsk,
      bids: [{ price: 0.39, size: 10 }],
      asks: [{ price: upAsk, size: 10 }],
      minOrderSize: minimumSize,
    },
    {
      tokenId: "down-token",
      outcome: "Down",
      outcomeIndex: 1,
      bestBid: 0.59,
      bestAsk: downAsk,
      bids: [{ price: 0.59, size: 10 }],
      asks: [{ price: downAsk, size: 10 }],
      minOrderSize: minimumSize,
    },
  ];
}
